# Generated by Django 4.2.4 on 2023-08-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='header_images/')),
            ],
        ),
    ]
