# Generated by Django 4.2.4 on 2023-08-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tokensale_alter_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensale',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tokensale',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tokensale',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tokensale',
            name='seconds',
            field=models.IntegerField(),
        ),
    ]
